<a href="https://colab.research.google.com/github/shreya-t-nagappanavar/practice_demo/blob/main/1_introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [4]:
lst = [1,2,3,4,5]

In [6]:
type(lst)

list

In [7]:
arr = np.array(lst)

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim

1

In [11]:
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
arr.dtype

dtype('int64')

In [14]:
zeros = np.zeros((3,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
ones = np.ones((3,5))

In [18]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])