<a href="https://colab.research.google.com/github/shreya-t-nagappanavar/practice_demo/blob/main/Array_of_Sorting_and_Merging_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array Sorting

In [1]:
import numpy as np

In [6]:
arr = np.array([[7,3,4,5,2],[8,2,5,4,1],[9,8,6,4,3]])

In [7]:
arr

array([[7, 3, 4, 5, 2],
       [8, 2, 5, 4, 1],
       [9, 8, 6, 4, 3]])

In [8]:
np.sort(arr , axis = 1, kind = 'mergesort')

array([[2, 3, 4, 5, 7],
       [1, 2, 4, 5, 8],
       [3, 4, 6, 8, 9]])

In [9]:
np.sort(arr , axis = 0, kind = 'mergesort')

array([[7, 2, 4, 4, 1],
       [8, 3, 5, 4, 2],
       [9, 8, 6, 5, 3]])

In [10]:
np.sort(arr , axis = 1, kind = 'heapsort')

array([[2, 3, 4, 5, 7],
       [1, 2, 4, 5, 8],
       [3, 4, 6, 8, 9]])

In [11]:
np.sort(arr , axis = 0, kind = 'quicksort')

array([[7, 2, 4, 4, 1],
       [8, 3, 5, 4, 2],
       [9, 8, 6, 5, 3]])

In [12]:
np.sort(arr , kind = 'quicksort')  # No axis then it will sort in row-wise

array([[2, 3, 4, 5, 7],
       [1, 2, 4, 5, 8],
       [3, 4, 6, 8, 9]])

In [13]:
np.sort(arr , kind = 'mergesort')

array([[2, 3, 4, 5, 7],
       [1, 2, 4, 5, 8],
       [3, 4, 6, 8, 9]])

# Array Merging

In [14]:
import numpy as np

In [15]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[4,5,6,7],[3,4,5,9]])

In [16]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2

array([[4, 5, 6, 7],
       [3, 4, 5, 9]])

In [18]:
np.vstack((arr1 , arr2)) #Concateninating

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7],
       [3, 4, 5, 9]])

In [19]:
np.vstack((arr2 , arr1)) #v for verticle h for horizontal

array([[4, 5, 6, 7],
       [3, 4, 5, 9],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.hstack((arr1 , arr2))

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [5, 6, 7, 8, 3, 4, 5, 9]])

In [22]:
np.hstack((arr1 , arr1))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [23]:
np.concatenate((arr1 , arr2) ,axis = 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7],
       [3, 4, 5, 9]])

In [24]:
np.concatenate((arr1 , arr2) ,axis = 1)

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [5, 6, 7, 8, 3, 4, 5, 9]])

In [26]:
arr = np.array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7],
       [3, 4, 5, 9]])

In [27]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7],
       [3, 4, 5, 9]])

In [28]:
np.hsplit(arr,2)

[array([[1, 2],
        [5, 6],
        [4, 5],
        [3, 4]]),
 array([[3, 4],
        [7, 8],
        [6, 7],
        [5, 9]])]

In [29]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[4, 5, 6, 7],
        [3, 4, 5, 9]])]

In [31]:
np.hsplit(arr,4)

[array([[1],
        [5],
        [4],
        [3]]),
 array([[2],
        [6],
        [5],
        [4]]),
 array([[3],
        [7],
        [6],
        [5]]),
 array([[4],
        [8],
        [7],
        [9]])]