<a href="https://colab.research.google.com/github/shreya-t-nagappanavar/practice_demo/blob/main/Array_Slicing_DAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
arr = np.array([1,2,3,5,6,7,8,9])

In [11]:
 arr[4]

6

In [12]:
arr[-4]

6

In [13]:
arr[ : ]

array([1, 2, 3, 5, 6, 7, 8, 9])

In [14]:
arr[5: ]

array([7, 8, 9])

In [15]:
arr[:-3]

array([1, 2, 3, 5, 6])

In [16]:
arr = np.array([[1,2,3,5],[6,7,8,9],[8,7,6,5],[4,3,2,1]])

In [17]:
arr

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [18]:
arr[ : , :1 ]

array([[1],
       [6],
       [8],
       [4]])

In [25]:
arr[ : , : ]

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [20]:
arr[ :2 , : ]

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [21]:
arr[ :2 , : 3]

array([[1, 2, 3],
       [6, 7, 8]])

In [22]:
arr[ :2 , : 5]

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [23]:
arr[1,1]

7

In [26]:
arr[2,3]

5

In [27]:
arr[1:,1:]

array([[7, 8, 9],
       [7, 6, 5],
       [3, 2, 1]])