<a href="https://colab.research.google.com/github/shreya-t-nagappanavar/practice_demo/blob/main/Automating_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [6]:
c = 0
for i in lst:
  if i > 5 :
    c += 1
print(c)

5


In [7]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
lst < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [11]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [12]:
len(lst[lst > 5])

5

In [13]:
print(len(lst[lst % 3 == 0]))
print(lst[lst % 3 == 0])

3
[3 6 9]
