<a href="https://colab.research.google.com/github/shreya-t-nagappanavar/practice_demo/blob/main/Copy_of_Arithmetic_operation_on_Array_and_multiple_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [ ]:
arr - 1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
print(arr + 1)
print(arr - 1)
print(arr * 1)
print(arr / 1)
print(arr % 1)
print(arr ** 2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]


In [ ]:
arr += 1

In [ ]:
arr

array([2, 3, 4, 5, 6, 7])

In [ ]:
arr -= 1

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr *= 2

In [ ]:
arr

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr.max()

12

In [ ]:
arr.min()

2

In [ ]:
arr.sort()

In [ ]:
print(arr)

[ 2  4  6  8 10 12]


In [ ]:
arr = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.max(axis = 0) #Maximum value in colun wise

array([7, 8, 9])

In [ ]:
 arr.max(axis = 1) #Maximum value in row wise

array([3, 6, 9])

In [ ]:
arr.min(axis = 1) #minimum value in row wise

array([1, 4, 7])

In [ ]:
arr.min(axis = 0) #minimum value in colun wise

array([1, 2, 3])

In [ ]:
arr.sum()

45

# Multiple Array Operations

In [ ]:
arr1 = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

arr2 = np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
 arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
 arr1 * arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [ ]:
 arr1 ** arr2

array([[   1,  256, 2187],
       [4096, 3125, 1296],
       [ 343,   64,    9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
 arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2:5]

array([3, 4, 5])

In [ ]:
arr[:-1]

array([1, 2, 3, 4, 5])

In [ ]:
arr[-3:-1]

array([4, 5])

In [ ]:
 arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[:1,:]

array([[1, 2, 3]])

In [ ]:
arr1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
arr1[1:2,1:2]

array([[5]])