<a href="https://colab.research.google.com/github/shreya-t-nagappanavar/practice_demo/blob/main/Reshape_and_Random_Number_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.random((3,3))

array([[0.23099084, 0.83717474, 0.73873415],
       [0.31814732, 0.02703684, 0.10048816],
       [0.84633524, 0.0038692 , 0.20029504]])

In [5]:
np.random.random()

0.9387788825347955

In [6]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
arr = np.random.random((6,3))

In [12]:
arr

array([[0.52995289, 0.85114581, 0.11698541],
       [0.14649199, 0.0378543 , 0.05501215],
       [0.65687368, 0.21699668, 0.40747226],
       [0.98740409, 0.10996246, 0.75265263],
       [0.80949294, 0.10987534, 0.00456709],
       [0.82750517, 0.70634104, 0.90635195]])

In [14]:
arr = np.reshape(arr,(3,6))

In [15]:
arr

array([[0.52995289, 0.85114581, 0.11698541, 0.14649199, 0.0378543 ,
        0.05501215],
       [0.65687368, 0.21699668, 0.40747226, 0.98740409, 0.10996246,
        0.75265263],
       [0.80949294, 0.10987534, 0.00456709, 0.82750517, 0.70634104,
        0.90635195]])

In [16]:
arr.flatten()

array([0.52995289, 0.85114581, 0.11698541, 0.14649199, 0.0378543 ,
       0.05501215, 0.65687368, 0.21699668, 0.40747226, 0.98740409,
       0.10996246, 0.75265263, 0.80949294, 0.10987534, 0.00456709,
       0.82750517, 0.70634104, 0.90635195])